### ISSUE TITLE
[US 12, US 13: Adding Transaction Details] Setting fuel quantity to blank causes "Discount Price" to display NaN

### ISSUE THREAD

**Issue by ianracoma** [STSWENG-T1-AY2122-AWS-CodeBuild/powerzone-inventory#107]
**Defect ID # 19**

**Description:**
When the user erases the contents of the fields for inputting fuel quantities in the "Add Transaction" screen, the Discount Price displays "NaN" as its value.

**Build/Platform:** Google Chrome

**Steps to Reproduce:**
1. Log in to an existing administrator or transaction cashier account
2. Open the transactions page
3. Click the "Add Transaction" button
4. Empty the contents of any of the quantity fields for the various fuels

**Actual Results:**
The Discounted Price field should show 0.00

**Expected Results:**
The Discounted Price field shows NaN

**Comment by memgonzales** [comment]
This [pull request](https://github.com/STSWENG-T1-AY2122-AWS-CodeBuild/powerzone-inventory/pull/106) addresses this issue.
