### ISSUE TITLE
[US 14, US 15: Editing Transaction Details] "Amount exceeds available fuel" message shows when a product quantity in a transaction is blank

### ISSUE THREAD

**Issue by j-gaba** [STSWENG-T1-AY2122-AWS-CodeBuild/powerzone-inventory#108]
**Defect ID # 020**

**Description:**
Using either an administrator or transaction cashier account to edit a transaction, replacing any of the product quantity values with a blank will display the "Amount exceeds available fuel" error message.

**Build/Platform:** Google Chrome

**Steps to Reproduce:**

1. Log in to an existing administrator or transaction cashier account
2. Open the transactions page
3. If no transactions exist yet, create a valid transaction
4. Edit the transaction and empty the quantity of any of the products

**Actual Results:**
The system will display an error message stating that the "Amount exceeds available fuel".

**Expected Results:**
The system should not show the error message since there is no inputted number.

**Comment by memgonzales** [comment]
This [pull request](https://github.com/STSWENG-T1-AY2122-AWS-CodeBuild/powerzone-inventory/pull/106) addresses this issue.
