### ISSUE TITLE
[US41: Editing Account Username] Editing usernames will only work if the change involves a capital letter or 2 or more characters were added or changed

### ISSUE THREAD

**Issue by ianracoma** [STSWENG-T1-AY2122-AWS-CodeBuild/powerzone-inventory#57]
**Defect ID # 003**

**Description:**
When editing an existing account as an inventory manager, delivery manager, or transaction cashier, the system does not allow the user to successfully make changes to their username unless the new username includes a capital letter (either as an additional character or by changing an existing character), or if the new username has 2 or more characters changed or added.

**Build/Platform:** Google Chrome

**Steps to Reproduce:**

1. Log in to an existing inventory manager, delivery manager, or transaction cashier account.
2. Click on "Account" on the home page.
3. Perform any but only one of the following changes:
    - Change only one character to any non-capital letter
    - Add only one non-capital letter
4. Enter accepted inputs for the remaining input fields.

**Actual Results:**
The confirm button remains inactive and cannot be clicked.

**Expected Results:**
The confirm button should become active once the password fields have been given appropriate and correct values.

**Comment by memgonzales** [comment]
This [pull request](https://github.com/STSWENG-T1-AY2122-AWS-CodeBuild/powerzone-inventory/pull/61#issue-1095274225) addresses this issue.
