### ISSUE TITLE
[US26, US27, US28, US29: Filtering Inventory Page] Clicking the reset button after filtering the inventory by sorting does not reset the order of the displayed items

### ISSUE THREAD

**Issue by j-gaba** [STSWENG-T1-AY2122-AWS-CodeBuild/powerzone-inventory#58]
**Defect ID # 004**

**Description:**
When using any valid account and accessing the inventory page, clicking on the reset button after filtering the items by sorting does not reset the order of the displayed items.

**Build/Platform:** Google Chrome

**Steps to Reproduce:**
1. Log in to an existing account.
2. Click on "Inventory" on the home page.
2. Select one of the radio buttons for sorting in the "Filter Inventory" Section.
3. Click on the "Reset" button.

**Actual Results:**
The system does not reset the inventory list to its original order.

**Expected Results:**
The system displays the inventory list in its order before the sort operation.

**Comment by memgonzales** [comment]
This [pull request](https://github.com/STSWENG-T1-AY2122-AWS-CodeBuild/powerzone-inventory/pull/63#issue-1095308595) addresses this issue.
