### ISSUE TITLE
[US26, US27, US28, US29: Price Display] Whole numbers in the "Price Purchased" fields do not show decimal values.

### ISSUE THREAD

**Issue by ianracoma** [STSWENG-T1-AY2122-AWS-CodeBuild/powerzone-inventory#59]
**Defect ID # 005**

**Description:**
When using any valid account and displaying the inventory page, when an entry in the price purchased field shows a whole number, the decimal part of the value is not displayed (i.e. there is no ".00" after the value).

**Build/Platform:** Google Chrome

**Steps to Reproduce:**

1. Log in to an existing account.
2. Click on "Inventory" on the home page.
3. View any entry showing a whole number for the "Price Purchased" column

**Actual Results:**
The whole number does not display any decimal value.

**Expected Results:**
The whole number should still have ".00" at its end.

**Comment by memgonzales** [comment]
This [pull request](https://github.com/STSWENG-T1-AY2122-AWS-CodeBuild/powerzone-inventory/pull/64#issue-1095314397) addresses this issue.
