### ISSUE TITLE
[US32, US33: Editing Stock Attributes] Edits to the "Purchased Quantity (L)" attribute does not reflect in the system

### ISSUE THREAD

**Issue by j-gaba** [STSWENG-T1-AY2122-AWS-CodeBuild/powerzone-inventory#72]
**Defect ID # 006**

**Description:**
When using either an administrator or inventory manager account to edit an inventory stock, changes to the "Purchased Quantity (L)" field do not reflect in the system.

**Build/Platform:** Google Chrome

**Steps to Reproduce:**

1. Log in to an existing administrator or inventory manager account.
2. Click on "Inventory" on the home page.
3. Click on the "Edit" button for one of the inventory stocks.
4. Change the "Purchased Quantity" to any integer aside from the original value.
5. Press the "Confirm" button to submit the change.

**Actual Results:**
The system accepts the change but does not reflect the new "Purchased Quantity" of the edited inventory stock.

**Expected Results:**
The system should reflect the change in the "Purchased Quantity" of the inventory stock after submitting the form.

**Comment by hyleene** [comment]
This [pull request](https://github.com/STSWENG-T1-AY2122-AWS-CodeBuild/powerzone-inventory/pull/73#issue-1110456908) addresses this issue.
