### ISSUE TITLE
[US12, US13, US14, US15, US20, US21, US22, US23, US24, US25: Transaction and Delivery Log Customer Number] Mozilla allows Customer Number Field to accept letter inputs

### ISSUE THREAD

**Issue by ianracoma** [STSWENG-T1-AY2122-AWS-CodeBuild/powerzone-inventory#74]
**Defect ID # 007**

**Description:**
Mozilla Firefox allows letters to be inputted in the "Customer Number" field in the "Customer Number" field in the edit page for deliveries and transactions, and the add page for transactions.

**Build/Platform:** Mozilla Firefox

**Steps to Reproduce:**
1) Open Mozilla Firefox and log in to the site as an administrator.
2) Access either the delivery page or transaction page.
3) For the delivery page, edit an existing delivery. For the transaction page, either edit an existing transaction or add a new one.
4) Input any string of letters in the "Customer Number" field.

**Actual Results:**
The "Customer Number" field allows the user to input letters.

**Expected Results:**
The "Customer Number" field should not update to show the letters being inputted.

**Comment by memgonzales** [comment]
In Firefox 96 (latest release), the behavior of `<input type = "number">` does not prohibit non-numerical input from being entered on keypress. A [bug report](https://bugzilla.mozilla.org/show_bug.cgi?id=1398528) has been submitted to Mozilla. 

**Nevertheless, the submit button remains disabled**, preventing the submission of an invalid customer number value:

![image](https://user-images.githubusercontent.com/44253974/150628411-e0697dea-f1fa-40c1-bc7a-06d2f86e5180.png)
