### ISSUE TITLE
[US12, US13, US14, US15, US20, US21, US22, US23, US24, US25: Transaction and Delivery Log Customer Number] Specify error in "Customer Number" field

### ISSUE THREAD

**Issue by ianracoma** [STSWENG-T1-AY2122-AWS-CodeBuild/powerzone-inventory#75]
**Defect ID # 008**

**Description:**
The error message shown when an invalid number is inputted in the "Customer Number" field does not specify the nature of the error.

**Build/Platform:** Google Chrome, Mozilla Firefox

**Steps to Reproduce:**
1) Log in to the site as an administrator.
2) Access either the delivery page or transaction page.
3) For the delivery page, edit an existing delivery. For the transaction page, either edit an existing transaction or add a new one.
4) Enter a number that does not fit within the 7-15 length restriction.

**Actual Results:**
The error for the "Customer Number" field display "Invalid Phone Number"

**Expected Results:**
The error for the "Customer Number" field should indicate that the phone number should have a length between 7 to 15 digits.

**Comment by memgonzales** [comment]
This [pull request](https://github.com/STSWENG-T1-AY2122-AWS-CodeBuild/powerzone-inventory/pull/77) addresses this issue.
