### ISSUE TITLE
[US14, US15: Editing Transaction Details] Changing the status of a previously cancelled transaction back to "Pending" when there is insufficient product quantity allows the status change to push through

### ISSUE THREAD

**Issue by j-gaba** [STSWENG-T1-AY2122-AWS-CodeBuild/powerzone-inventory#76]
**Defect ID # 009**

**Description:**
Using either an administrator or transaction cashier account to edit a transaction, changing the status of a previously cancelled transaction back to "Pending" when there is insufficient product quantity allows the status change to still be accepted by the system.

**Build/Platform:** Google Chrome

**Steps to Reproduce:**

1. Log in to an existing administrator or transaction cashier account.
2. Click on "Transaction" on the home page.
3. Add a transaction with the maximum amount of quantity allowed for "Gasoline" (i.e., the currently available total amount shown on the "Inventory" page).
4. Set the newly created transaction's status to "Cancelled".
5. Create another transaction similar to what was done for number 3.
6. Set the former transaction's status back to "Pending".
7. Refresh the page.

**Actual Results:**
The system shows that the first transaction's status is changed to "Pending" despite having insufficient product quantity for "Gasoline".

**Expected Results:**
The system should display an error message stating that there is not enough product quantity to change the transaction's status back to "Pending".

**Comment by memgonzales** [comment]
This [pull request](https://github.com/STSWENG-T1-AY2122-AWS-CodeBuild/powerzone-inventory/pull/82) addresses this issue.
