### ISSUE TITLE
[US 23, US 24, US 25: Delivery Status] Inventory managers can edit the status of a delivery

### ISSUE THREAD

**Issue by ianracoma** [STSWENG-T1-AY2122-AWS-CodeBuild/powerzone-inventory#78]
**Defect ID # 10**

**Description:**
Users with the inventory manager role can edit the status of an existing delivery.

**Build/Platform:** Google Chrome

**Steps to Reproduce:**
1) Log in as any user with the "Inventory Manager" role.
2) Access the "Deliveries" page.
3) Click on the icon on the status column of any delivery.
4) Change the status of the delivery to anything other than what is currently selected.

**Actual Results:**
The status of the delivery is updated and is reflected on the database,

**Expected Results:**
Users with the Inventory manager role should not have access to the feature for editing delivery statuses.

**Comment by memgonzales** [comment]
This [pull request](https://github.com/STSWENG-T1-AY2122-AWS-CodeBuild/powerzone-inventory/pull/82) addresses this issue.
