### ISSUE TITLE
[US14, US15: Editing Transaction Details] Changing the status of two cancelled transactions back to "Pending" when there is only enough product quantity for one transaction allows the status change to push through

### ISSUE THREAD

**Issue by j-gaba** [STSWENG-T1-AY2122-AWS-CodeBuild/powerzone-inventory#83]
**Defect ID # 011**

**Description:**
Using either an administrator or transaction cashier account to edit a transaction, changing the status of two cancelled transactions back to "Pending" when there is only enough product quantity for one transaction allows both status changes to still be accepted by the system.

**Build/Platform:** Google Chrome

**Steps to Reproduce:**

1. Log in to an existing administrator or transaction cashier account.
2. Click on "Transaction" on the home page.
3. Add a transaction with the maximum amount of quantity allowed for "Gasoline" (i.e., the currently available total amount shown on the "Inventory" page).
4. Set the newly created transaction's status to "Cancelled".
5. Add another transaction similar to what was done for number 3.
6. Set the status of the transaction created in number 5 to "Cancelled" as well.
7. Refresh the page.
8. Set the status of the first transaction to "Pending".
9. Set the status of the second transaction to "Pending"
10. Refresh the page.

**Actual Results:**
The system shows that the second transaction's status is changed to "Pending" as well despite having insufficient product quantity for "Gasoline" after the first transaction was set to "Pending".

**Expected Results:**
The system should display an error message stating that there is not enough product quantity to change the second transaction's status back to "Pending" once the first transaction's status was changed.

**Comment by hyleene** [comment]
This [pull request](https://github.com/STSWENG-T1-AY2122-AWS-CodeBuild/powerzone-inventory/pull/86#issue-1123887298) addresses this issue.
