### ISSUE TITLE
[US14, US15: Editing Transaction Details] Editing fuel values in the edit transaction page does not work if the new value is higher than the current inventory count for that fuel, despite it being valid

### ISSUE THREAD

**Issue by ianracoma** [STSWENG-T1-AY2122-AWS-CodeBuild/powerzone-inventory#84]
**Defect ID # 12**

**Description:**
When attempting to change the quantity of a fuel type reserved for a transaction, the edit screen will not permit the user to edit the value if the new value inputted is higher than the current inventory count for that fuel (as seen in the inventory screen), despite it being a valid value.

**Build/Platform:** Google Chrome / Firefox

**Steps to Reproduce:**

1. Log in as an administrator or transaction cashier.
2. Navigate to the "Transaction" page.
3. Open the edit transaction page for any transaction
4. Edit the value for any fuel type such that the value is higher than the current inventory count for that fuel but lower than or equal to the sum of the transaction's original value and the inventory count combined (i.e. If the fuel reserved for a transaction is 50 L gasoline, and the inventory has 60 L extra gasoline, edit the value to be anywhere between 61 L to 110 L)

The issue can also be replicated when attempting to reduce a reserved fuel value, but the new value is higher than the inventory count for that fuel

1. Follow steps 1 and 2 in the previous list
2. If no such transaction exists yet, create a transaction with a fuel quantity that is greater than half that fuel's current inventory quantity but less than or equal to its actual quantity (i.e. If gasoline has a current inventory value of 50 L, the quantity should be between 26 L and 50 L)
3. Open the edit transaction page for that transaction
4. Attempt to set the value to anything less than or equal to the current quantity declared in the transaction, but greater than the current inventory stock for that fuel (i.e. if the transaction reserved 30 L fuel, and the current inventory quantity is 20 L, set the quantity to any value between 21 L and 30 L)

**Actual Results:**
The "Edit Transaction" page will show the error message indicating that there's too little fuel in the inventory.

**Expected Results:**
The "Edit Transaction" page should allow the user to submit the new value.

**Comment by memgonzales** [comment]
This [pull request](https://github.com/STSWENG-T1-AY2122-AWS-CodeBuild/powerzone-inventory/pull/85) addresses this issue.
