### ISSUE TITLE
[US14, US15: Editing Transaction Details] Editing a transaction with fuel quantities set higher than the current inventory quantity will automatically set its transaction to "Cancelled", and cannot be changed to "Pending"

### ISSUE THREAD

**Issue by ianracoma** [STSWENG-T1-AY2122-AWS-CodeBuild/powerzone-inventory#87]
**Defect ID #13**

**Description:**
When attempting to edit a transaction with a fuel value higher than the inventory count for that fuel, the status of the transaction in the "Edit transaction" page is set to "Cancelled" and cannot be set to "Pending".

**Build/Platform:** Google Chrome

**Steps to Reproduce:**
1) Log in to the site as either a transaction cashier or administrator
2) Access the transactions page
3) If no transactions exist yet, create a transaction with a fuel quantity that causes the inventory's quantity to be lower than the assigned fuel quantity.
4) Edit the transaction.
5) Check the status of the transaction on the "Edit Transaction" page and attempt to change it.

**Actual Results:**
The transaction is automatically set to "Cancelled" and cannot be changed back to "Pending"

**Expected Results:**
The transaction should not be set to "Cancelled" and there should still be an option to change it to "Pending"

**Comment by memgonzales** [comment]
This [pull request](https://github.com/STSWENG-T1-AY2122-AWS-CodeBuild/powerzone-inventory/pull/89) addresses this issue.
