### ISSUE TITLE
[US14, US15: Editing Transaction Details] Editing transactions with values for fuels currently 0 in the inventory prevents confirmation in certain situations

### ISSUE THREAD

**Issue by ianracoma** [STSWENG-T1-AY2122-AWS-CodeBuild/powerzone-inventory#88]
**Defect ID # 14**

**Description:**
Potentially an extension of #87 .
When editing a transaction with a quantity for a fuel that is currently 0 in the inventory, when attempting to edit the value to a higher value (triggering the error message) then returning the value to the original value or anything lower, the confirm button continues to be disabled.

Editing any other fields in transactions that fit this description will also exhibit the same behavior.

**Build/Platform:** Google Chrome

**Steps to Reproduce:**
1) Log in as a transaction cashier or administrator
2) Open the transactions page
3) If no transaction exists yet, create a transaction in which one of its fuel values will cause the inventory to have 0 L for that fuel
4) Edit the described transaction
5) Set the value of the fuel with 0 L in inventory to anything higher than what is currently set
6) Set the value of the fuel again to either the original value or anything lower.

Alternatively:

5) Change any value in the transaction details to anything valid.

**Actual Results:**
The "Confirm" button does not become re-enabled.

**Expected Results:**
The "Confirm" button should be re-enabled.

**Comment by memgonzales** [comment]
This [pull request](https://github.com/STSWENG-T1-AY2122-AWS-CodeBuild/powerzone-inventory/pull/89) addresses this issue.
