### ISSUE TITLE
[US14, US15: Editing Transaction Details] Editing transaction quantities with values exceeding the stock amount displays the correct error message but does not disable the confirm button

### ISSUE THREAD

**Issue by j-gaba** [STSWENG-T1-AY2122-AWS-CodeBuild/powerzone-inventory#91]
**Defect ID # 15**

**Description:**
When editing a transaction with a quantity of fuel that exceeds the maximum amount allowed by the inventory stock, the error message is triggered but the confirm button remains enabled.

**Build/Platform:** Google Chrome

**Steps to Reproduce:**
1) Log in as a transaction cashier or administrator
2) Open the transactions page
3) If no transactions exist yet, create a valid transaction
4) Edit the created transaction, and set the quantity of any of the products to 999999 or any value greater than the maximum allowed quantity for that product

**Actual Results:**
The appropriate error message is shown but the "Confirm" button remains enabled.

**Expected Results:**
The "Confirm" button should be disabled once the error message is displayed.

**Comment by memgonzales** [comment]
This [pull request](https://github.com/STSWENG-T1-AY2122-AWS-CodeBuild/powerzone-inventory/pull/90) addresses this issue.
