### ISSUE TITLE
[US05: Transaction Cashier Feature Access] Transaction cashiers cannot edit delivery details

### ISSUE THREAD

**Issue by j-gaba** [STSWENG-T1-AY2122-AWS-CodeBuild/powerzone-inventory#94]
**Defect ID # 16**

**Description:**
When logged in as a transaction cashier, the deliveries page does not allow the user to edit an existing delivery.

**Build/Platform:** Google Chrome

**Steps to Reproduce:**
1) Log in as a transaction cashier
2) Open the transactions page
3) If no transactions exist yet, create a valid transaction
4) Open the deliveries page

**Actual Results:**
The edit delivery button is not visible for any existing delivery.

**Expected Results:**
The edit delivery button should be visible and enabled for all deliveries on the page.

**Comment by memgonzales** [comment]
This [pull request](https://github.com/STSWENG-T1-AY2122-AWS-CodeBuild/powerzone-inventory/pull/93) addresses this issue.
