### ISSUE TITLE
[US23, US24, US25: Editing Delivery Details] Unable to change the delivery status from "Pending" to "Completed" when at least one product involved in the transaction is out of stock

### ISSUE THREAD

**Issue by j-gaba** [STSWENG-T1-AY2122-AWS-CodeBuild/powerzone-inventory#95]
**Defect ID # 017**

**Description:**
Using either an administrator, delivery manager, or transaction cashier account to edit a delivery, changing the status of one delivery from "Pending" to "Completed" when there is not enough quantity for at least one of the involved products will disable the "Completed" button.

**Build/Platform:** Google Chrome

**Steps to Reproduce:**

1. Log in to an existing administrator, delivery manager, or transaction cashier account.
2. Open the transactions page.
3. Add a transaction with the maximum amount of quantity allowed for "Gasoline" (i.e., the currently available total amount shown on the "Inventory" page).
4. Open the deliveries page
5. Click on the "Status" button to open the menu for changing delivery status or click on the "Edit" button to change the status from the edit delivery page.

**Actual Results:**
In attempting to modify the status from either the pop-up menu or the edit delivery page, the system only allows the user to change the status to "Cancelled".

**Expected Results:**
The system should still allow the user to change the status to "Completed".

**Comment by memgonzales** [comment]
This [pull request](https://github.com/STSWENG-T1-AY2122-AWS-CodeBuild/powerzone-inventory/pull/96) addresses this issue.
