### ISSUE TITLE
[US 14, US 15: Editing Transaction Details] "Insufficient fuel in the inventory" message persists on all transactions after it has been viewed once

### ISSUE THREAD

**Issue by ianracoma** [STSWENG-T1-AY2122-AWS-CodeBuild/powerzone-inventory#98]
**Defect ID # 18**

**Description:**
When a cancelled transaction shows the "Insufficient fuel in the inventory" message, the message appears for all transactions when hovering over the "Pending" button when changing its status from the main transaction screen.

**Build/Platform:** Google Chrome

**Steps to Reproduce:**
A video has been provided for easier demonstration.

https://user-images.githubusercontent.com/75113133/152644723-b02adcd1-9773-49c5-83bb-4e4cf41b71c6.mp4

**Actual Results:**
The error message appears on transactions that are set to "Pending" or on cancelled transactions that can be set to "Pending"

**Expected Results:**
The error message should not appear on transactions that are set to "Pending" or on cancelled transactions that can be set to "Pending"

**Comment by memgonzales** [comment]
This [pull request](https://github.com/STSWENG-T1-AY2122-AWS-CodeBuild/powerzone-inventory/pull/99) addresses this issue.
